blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('update/<slug:slug>', BlogUpdateView.as_view(), name='update'),
    path('view/<slug:slug>', BlogDetailView.as_view(), name='view'),
    path('delete/<slug:slug>/', BlogDeleteView.as_view(), name='delete')

]

config/config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('catalog.urls', 'catalog'), namespace='catalog')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('users/', include(('users.urls', 'users'), namespace='users')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    """Класс для создания модели блоговой записи
    """

    title = models.CharField(max_length=150, verbose_name='Заголовок', help_text='Введите название статьи')
    slug = models.CharField(max_length=150, verbose_name='slug')
    content = models.TextField(verbose_name='Содержимое', **NULLABLE, help_text='Добавьте содержимое')
    preview = models.ImageField(upload_to='blog_foto', verbose_name='Изображение', **NULLABLE,
                                help_text='Добавьте изображение')
    date_of_creation = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Признак публикации')
    view_counter = models.PositiveIntegerField(verbose_name='Количество просмотров', default=0)

    class Meta:
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'
        ordering = ('date_of_creation', 'is_published',)

    def __str__(self):
        return self.title

blog/views.py
from pytils.translit import slugify
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from blog.models import Blog


# Create your views here.
class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'slug', 'content', 'preview', 'created_at')
    success_url = reverse_lazy('materials:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()
        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'slug', 'content', 'preview', 'created_at')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset()
        queryset = queryset.filter(published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def __init__(self, **kwargs):
        super().__init__(kwargs)
        self.object = None

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views += 1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'content', 'preview', 'is_published', 'view_counter')

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('slug')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('materials:list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="card">
              <div class="card-body">
                  <form method="post">
                      {% csrf_token %}
                      {{ form.as_p }}
                      <p>Удалить Продукт "{{ object.title }}?"</p>
                      <button type="submit" class="btn btn-primary">Подтвердить</button>
                      <a href="{% url 'blog:list' %}" class="btn btn-success">Отменить</a>
                  </form>
              </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row text-center">
    <div class="col-4">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                Материал {{object.title}} {{object.slug}}
                <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                <h4 class="my-0 font-weight-normal">{{ object.content }}</h4>
                <h4 class="my-0 font-weight-normal">{{ object.preview }}</h4>
                <h4 class="my-0 font-weight-normal">{{ object.slug }}</h4>
            </div>
            <div class="card-body">
                <a class="btn btn-primary" role="button"
                   href="{% url 'materials:list' %}">Назад</a>
            </div>
            Просмотры: {{object.views}}
        </div>
        <div class="coll-6">
            <img src="{{ product.imagery | media_filter }}">
        </div>
    </div>
    {% endblock %}
</div>

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card_body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p}}}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif%}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock%}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row text-center">
    <a class="btn btn-primary" role="button"
       href="{% url 'materials:create' %}">Создать</a>
    {% for product in object_list %}
    <div class="col-4">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                {% if product.imagery %}
                <img src="{{ product.imagery | media_filter }}">
                {% endif %}
                <h4 class="my-0 font-weight-normal">{{ product.category }}</h4>
            </div>
            <div class="card-body">
                <a class="btn btn-primary" role="button"
                   href="{% url 'blog:view' product.pk %}">Посмотреть</a>
                <a class="btn btn-primary" role="button"
                   href="{% url 'blog:edit' product.pk %}">Редактировать</a>
                <a class="btn btn-primary" role="button"
                   href="{% url 'blog:delete' product.pk %}">Удалить</a>
            </div>
        </div>

    </div>
    {% endfor %}
</div>
{% endblock %}