blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('update/<slug:slug>', BlogUpdateView.as_view(), name='update'),
    path('view/<slug:slug>', BlogDetailView.as_view(), name='view'),
    path('delete/<slug:slug>/', BlogDeleteView.as_view(), name='delete')

]

config/config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('catalog.urls', 'catalog'), namespace='catalog')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('users/', include(('users.urls', 'users'), namespace='users')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from .views import RegisterView, CustomPasswordResetView
from django.urls import path
from users import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='/users/login/'), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('email_confirm/<str:token>/', views.email_confirm, name='email_confirmed'),
    path('custom-password-reset/', CustomPasswordResetView.as_view(), name='custom_password_reset'),
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

users/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models

class UserManager(BaseUserManager):
    def get_by_natural_key(self, email):
        return self.get(email=email)

class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Email')
    phone = models.CharField(max_length=35, verbose_name='Телефон', blank=True, null=True,
                             help_text='Введите номер телефона')
    country = models.CharField(max_length=50, verbose_name='Страна', blank=True, null=True, help_text='Введите страну')
    avatar = models.ImageField(upload_to="users/avatars", blank=True, null=True, help_text='Загрузите свой аватар')
    token = models.CharField(max_length=64, unique=True, null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()  # Используем пользовательский менеджер

    def natural_key(self):
        return (self.email,)

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from users.models import User
from catalog.forms import StyleFormMixin
from django import forms


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'phone', 'country', 'avatar', 'token')

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['email'].required = True
        self.fields['token'].widget = forms.HiddenInput()


class PasswordResetRequestForm(forms.Form):
    email = forms.EmailField(label="Email", max_length=254)

users/views.py
import random
import string
import secrets
from django.core.mail import send_mail
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views import View
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages
from django.conf import settings
from .models import User
from .forms import CustomUserCreationForm


# Класс для регистрации пользователя
class RegisterView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/register.html'

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email_confirm/{token}'
        send_mail(
            'Подтверждение регистрации',
            f'Спасибо за регистрацию. Пожалуйста, подтвердите ваш аккаунт, перейдя по следующей ссылке: {url}',
            settings.DEFAULT_FROM_EMAIL,
            [user.email],
            fail_silently=False,
        )
        return super().form_valid(form)


def email_confirm(request, token):
    user = get_object_or_404(User, token=token)
    if not user.is_active:
        user.is_active = True
        user.token = ''  # Очистка токена после активации
        user.save()
        messages.success(request, 'Ваш аккаунт был активирован.')
        return redirect('users:login')  # Перенаправление на страницу входа
    else:
        messages.info(request, 'Аккаунт уже был активирован.')
        return redirect('users:login')


# Класс для сброса пароля
def send_email(email, new_password):
    subject = 'Your new password'
    message = f'Your new password is: {new_password}'
    from_email = settings.DEFAULT_FROM_EMAIL
    send_mail(subject, message, from_email, [email])


class CustomPasswordResetView(View):
    def post(self, request):
        email = request.POST.get('email')
        try:
            user = User.objects.get(email=email)
            new_password = self.generate_random_password()
            user.set_password(new_password)
            user.save()
            send_email(user.email, new_password)
            return JsonResponse(
                {'status': 'success', 'message': 'Password reset successfully. Check your email for the new password.'})
        except User.DoesNotExist:
            return JsonResponse({'status': 'error', 'message': 'User with this email does not exist.'})

    @staticmethod
    def generate_random_password(length=8):
        characters = string.ascii_letters + string.digits + string.punctuation
        return ''.join(random.choice(characters) for _ in range(length))

    @staticmethod
    def send_email(email, new_password):
        subject = 'Your new password'
        message = f'Your new password is: {new_password}'
        from_email = settings.DEFAULT_FROM_EMAIL
        send_mail(subject, message, from_email, [email])

users/templates/users/email_confirmed.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Подтверждение Email</title>
</head>
<body>
    <h1>Подтверждение Email</h1>
    <p>Спасибо за подтверждение вашего адреса электронной почты. Теперь вы можете использовать все функции нашего сайта.</p>
    <p><a href="{% url 'users:login' %}">Войти в систему</a></p>
</body>
</html>

users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Войти</button>
                    </div>
                </div>
            </div>
        </form>
        <!-- Отдельная форма для восстановления пароля -->
        <form method="post" action="{% url 'users:password_reset' %}">
            {% csrf_token %}
            <input type="email" name="email" required placeholder="Введите вашу электронную почту">
            <button type="submit">Восстановить пароль</button>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/logout.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body d-flex align-items-center">
                        <form method="get" action="{% url 'users:logout' %}">
                            <button type="submit" class="btn btn-primary">Выйти</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset.html
{% extends "base.html" %}

{% block content %}
  <h2>Reset Password</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Reset Password</button>
  </form>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends "base.html" %}

{% block content %}
  <h2>Password Reset Complete</h2>
  <p>Your password has been set. You can now <a href="{% url 'login' %}">log in</a> with the new password.</p>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends "base.html" %}

{% block content %}
  <h2>Enter New Password</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Reset Password</button>
  </form>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends "base.html" %}

{% block content %}
  <h2>Password Reset Done</h2>
  <p>An email has been sent with your new password.</p>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                       {{form.as_p}}
                        <button type="submit" class="btn btn-primary">
                            Регистрация
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}