blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('update/<slug:slug>', BlogUpdateView.as_view(), name='update'),
    path('view/<slug:slug>', BlogDetailView.as_view(), name='view'),
    path('delete/<slug:slug>/', BlogDeleteView.as_view(), name='delete')

]

catalog/urls.py
from django.urls import path, include
from catalog.views import (ContactsTemplateView, ProductListView, ProductDetailView,
                           ProductCreateView, ProductUpdateView, ProductDeleteView)
from .views import CategoryListView
from django.urls import path
from django.views.decorators.cache import cache_page

app_name = 'catalog'  # Добавление пространства имен для приложения

urlpatterns = [
    path('', ProductListView.as_view(), name='products_list'),
    path('contacts/', ContactsTemplateView.as_view(), name='contacts'),
    path('product/<int:pk>/', cache_page(60 * 15)(ProductDetailView.as_view()), name='product_detail'),
    path('product/add/', ProductCreateView.as_view(), name='product_create'),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('users/', include('users.urls')),
    path('categories/', CategoryListView.as_view(), name='category_list')
]

config/config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('catalog.urls', 'catalog'), namespace='catalog')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('users/', include(('users.urls', 'users'), namespace='users')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.conf import settings

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    """Модель для Категорий продукта"""

    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание', **NULLABLE)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('name',)

    def __str__(self):
        return self.name


class Product(models.Model):
    """Модель для продукта"""
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)
    preview = models.ImageField(upload_to='products_foto', verbose_name='Изображение', blank=True, null=True)
    category = models.ForeignKey('Category', related_name='products', on_delete=models.SET_NULL, null=True)
    price = models.IntegerField(verbose_name='Цена')
    date_of_creation = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    last_modified_date = models.DateField(auto_now=True, verbose_name='Дата изменения')
    view_counter = models.PositiveIntegerField(verbose_name='Счетчик просмотров',
                                               help_text="Укажите количество просмотров", default=0)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Владелец',
                              related_name='products')
    version = models.CharField(max_length=100, blank=True)
    # Добавляем новое поле is_published
    is_published = models.BooleanField(default=False, verbose_name='Опубликовано')

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ('name',)
        permissions = [
            ('cancel_publish_product', 'Может отменять публикацию продукта'),
            ('change_product_description', 'Может менять описание продукта'),
            ('change_product_category', 'Может менять категорию продукта'),
        ]

    def __str__(self):
        return self.name


class Version(models.Model):
    """Модель для версии продукта"""
    product = models.ForeignKey(Product, related_name='versions', verbose_name='Продукт', on_delete=models.CASCADE)
    number = models.PositiveIntegerField(verbose_name=' Номер версии', blank=True, null=True)
    name = models.CharField(max_length=150, verbose_name='Название версии')
    is_current = models.BooleanField(default=True, verbose_name='Признак актуальности')

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'
        ordering = ('name',)

    def __str__(self):
        return self.name

catalog/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm, BooleanField

from catalog.models import Product, Version


class StyleFormMixin:
    """Класс для стилизации форм"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():

            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, ModelForm):
    """Класс для создание форм для модели Продукт"""
    banned_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

    class Meta:
        model = Product
        fields = ('name', 'description', 'preview', 'category', 'price')

    def clean_name(self):
        """Метод для проверки валидации имени Продукта при создании нового объекта"""
        cleaned_data = self.cleaned_data['name']
        if cleaned_data.lower() in self.banned_words:
            raise ValidationError(f'Слова, запрещенные к использованию в названии продукта: '
                                  f'{str(self.banned_words)[1:-2]}')
        return cleaned_data

    def clean_description(self):
        """Метод для проверки валидации описания Продукта при создании нового объекта"""
        cleaned_data = self.cleaned_data['description']
        if cleaned_data.lower() in self.banned_words:
            raise ValidationError(f'Слова, запрещенные к использованию в описании продукта: '
                                  f'{str(self.banned_words)[1:-2]}')
        return cleaned_data


class VersionForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Version
        fields = ('id', 'product', 'name', 'number', 'is_current')

catalog/views.py
from django.http import HttpResponseForbidden
from django.forms.models import inlineformset_factory
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Version, Category
from catalog.servises import get_categories


class CategoryListView(ListView):
    model = Category
    template_name = 'category_list.html'
    context_object_name = 'categories'

    def get_queryset(self):
        return get_categories()


class ContactsTemplateView(TemplateView):
    template_name = 'catalog/contacts.html'

    def post(self, request, *args, **kwargs):
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(name, phone, message)
        return super().get(request, *args, **kwargs)


class ProductListView(ListView):
    """Класс для вывода страницы со всеми продуктами"""
    model = Product

    def get_context_data(self, *args, **kwargs):
        """Метод для получения версий Продукта и вывода только активной версии"""
        context = super().get_context_data(*args, **kwargs)
        products = self.get_queryset()
        for product in products:
            product.version = product.versions.filter(is_current=True).first()

        # Данная строчка нужна, чтобы в contex добавились новые данные о Продуктах
        context["object_list"] = products

        return context


class ProductDetailView(DetailView):
    """Класс для вывода страницы с одним продуктом по pk"""
    model = Product

    def get_object(self, queryset=None):
        """Метод для настройки работы счетчика просмотра продукта"""
        self.object = super().get_object(queryset)
        self.object.view_counter += 1
        self.object.save()
        return self.object


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:products_list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)

        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST)
        else:
            context_data['formset'] = VersionFormset()

        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        if form.is_valid() and formset.is_valid():
            self.object = form.save(commit=False)
            self.object.owner = self.request.user
            self.object.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    fields = ['description', 'category']
    template_name = 'catalog/product_form.html'

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if not request.user.has_perm('catalog.change_product_description') or \
                not request.user.has_perm('catalog.change_product_category') or \
                obj.owner != request.user:
            return HttpResponseForbidden("У вас нет разрешения на изменение этого продукта.")
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('catalog:product_detail', args=[self.get_object().pk])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)

        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)

        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']

        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:products_list')

    def dispatch(self, request, *args, **kwargs):
        if not request.user.has_perm('your_app_label.cancel_publish_product'):
            return HttpResponseForbidden("У вас нет разрешения на удаление этого продукта.")
        return super().dispatch(request, *args, **kwargs)

catalog/templates/catalog/add_product.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Добавление продукта</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Добавить продукт</button>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/contacts.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
        {% include 'includes/auth_buttons.html' %}
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/product_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="card">
              <div class="card-body">
                  <form method="post">
                      {% csrf_token %}
                      {{ form.as_p }}
                      <p>Вы хотите удалить Продукт "{{ object.name }}?"</p>
                      <button type="submit" class="btn btn-primary">Подтвердить</button>
                      <a href="{% url 'catalog:products_list' %}" class="btn btn-success">Отменить</a>
                  </form>
              </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
<div class="row text-center">
    <div class="col-4">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                {% if object.preview %}
                <img src="{{ object.preview.url }}" alt="{{ object.name }}">
                {% endif %}
                <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
            </div>
            <div class="card-body">
                <h4 class="my-0 font-weight-normal">{{ object.description | truncatewords:100 }}</h4>
                <h4 class="my-0 font-weight-normal">Цена {{ object.price }}</h4>
                <!-- Здесь добавляем новое поле версии -->
                <h4 class="my-0 font-weight-normal">Версия: {{ object.version }}</h4>
                <!-- Кнопка редактирования для владельца продукта -->
                {% if user.is_authenticated and object.owner == user %}
                <a href="{% url 'catalog:product_update' object.id %}">Редактировать</a>
                {% endif %}
                <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">
                            {% if object %}
                            Редактирование продукта
                             {% else %}
                            Создание нового продукта
                            {% endif %}
                        </h4>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </div>
                    <div class="card-footer">
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">
                            Версии продукта
                        </h4>
                    </div>
                    <div class="card-body">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                        {{ form.as_p }}
                        {% endfor %}
                    </div>
                    <div class="card-footer">
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
{% if user.is_authenticated %}
    <a href="{% url 'catalog:product_create' %}" class="btn btn-primary">Добавить продукт</a>
{% endif %}
<div class="row text-center">
    {% for product in object_list %}
    <div class="col-4">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                {% if product.imagery %}
                <img src="{{ product.imagery | media_filter }}">
                {% endif %}
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ product.category}}</h4>
                </div>
                <h4 class="my-0 font-weight-normal">{{ product.product_name }}</h4>
                <h4 class="my-0 font-weight-normal">{{ product.product_description | truncatewords:10 }}</h4>
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Цена {{ product.cost_product }} </h4>
                </div>
            </div>

            <div class="card-body">
                <a class="btn btn-primary" role="button"
                   href="{% url 'catalog:product_detail' product.pk %}">Посмотреть</a>

            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}